<?php
/**
 * Roles & capabilities for TM Members Area.
 *
 * Defines three membership roles and a set of custom capabilities that the
 * rest of the plugin gates on (instead of generic list_users/manage_options):
 *
 *   - Member    : manage own profile, RSVP to events.
 *   - Producer  : Member + search members, email/message members, manage events.
 *   - Executive : Producer + manage members and plugin settings (full access).
 *
 * Roles are (re)registered on demand and version-gated so capability changes
 * roll out without a manual deactivate/reactivate. Administrators always get
 * every TM capability mirrored onto them.
 */

if (!defined('ABSPATH')) {
    exit;
}

class STAGEKITWP_MEMBERS_Roles {

    /**
     * Bump when the capability map below changes so roles re-sync on load.
     */
    const CAPS_VERSION = '1.0.2';

    const OPTION_KEY = 'stagekitwp_members_roles_version';

    /**
     * Custom capabilities this plugin checks against.
     */
    const CAP_MANAGE_PROFILE  = 'stagekitwp_members_manage_profile';
    const CAP_RSVP_EVENTS     = 'stagekitwp_members_rsvp_events';
    const CAP_SEARCH_MEMBERS  = 'stagekitwp_members_search_members';
    const CAP_MESSAGE_MEMBERS = 'stagekitwp_members_message_members';
    const CAP_SEND_EMAIL      = 'stagekitwp_members_send_email';
    const CAP_MANAGE_EVENTS   = 'stagekitwp_members_manage_events';
    const CAP_MANAGE_MEMBERS  = 'stagekitwp_members_manage_members';
    const CAP_MANAGE_SETTINGS = 'stagekitwp_members_manage_settings';

    public static function init() {
        add_action('plugins_loaded', [__CLASS__, 'maybe_sync'], 6);
    }

    /**
     * Full capability map per role. Each role inherits the ones below it.
     */
    public static function capabilities() {

        $member = [
            self::CAP_MANAGE_PROFILE,
            self::CAP_RSVP_EVENTS,
            // Members can browse the opt-in directory and message each other.
            self::CAP_SEARCH_MEMBERS,
            self::CAP_MESSAGE_MEMBERS,
        ];

        $producer = array_merge($member, [
            self::CAP_SEND_EMAIL,
            self::CAP_MANAGE_EVENTS,
        ]);

        $executive = array_merge($producer, [
            self::CAP_MANAGE_MEMBERS,
            self::CAP_MANAGE_SETTINGS,
        ]);

        return [
            'stagekitwp_member'    => ['name' => 'Member',    'caps' => $member],
            'stagekitwp_producer'  => ['name' => 'Producer',  'caps' => $producer],
            'stagekitwp_executive' => ['name' => 'Executive', 'caps' => $executive],
        ];
    }

    /**
     * Primitive caps generated by the stagekitwp_event CPT (capability_type =
     * ['stagekitwp_event','stagekitwp_events'], map_meta_cap = true). Granting these lets a
     * role create/edit/delete/publish events in wp-admin.
     */
    public static function event_caps() {
        return [
            'edit_stagekitwp_event',
            'read_stagekitwp_event',
            'delete_stagekitwp_event',
            'edit_stagekitwp_events',
            'edit_others_stagekitwp_events',
            'publish_stagekitwp_events',
            'read_private_stagekitwp_events',
            'delete_stagekitwp_events',
            'delete_private_stagekitwp_events',
            'delete_published_stagekitwp_events',
            'delete_others_stagekitwp_events',
            'edit_private_stagekitwp_events',
            'edit_published_stagekitwp_events',
        ];
    }

    /**
     * Every custom capability, flat. Used to grant admins full access.
     */
    public static function all_caps() {
        return [
            self::CAP_MANAGE_PROFILE,
            self::CAP_RSVP_EVENTS,
            self::CAP_SEARCH_MEMBERS,
            self::CAP_MESSAGE_MEMBERS,
            self::CAP_SEND_EMAIL,
            self::CAP_MANAGE_EVENTS,
            self::CAP_MANAGE_MEMBERS,
            self::CAP_MANAGE_SETTINGS,
        ];
    }

    /**
     * Re-sync roles only when the capability map version changes.
     */
    public static function maybe_sync() {
        if (get_option(self::OPTION_KEY) === self::CAPS_VERSION) {
            return;
        }
        self::register_roles();
        update_option(self::OPTION_KEY, self::CAPS_VERSION);
    }

    /**
     * Create/update all roles and mirror caps onto administrator. Idempotent.
     */
    public static function register_roles() {

        foreach (self::capabilities() as $slug => $role) {

            // add_role() is a no-op if the role exists, so remove first to
            // guarantee the capability set matches the current map exactly.
            remove_role($slug);

            $caps = ['read' => true];
            foreach ($role['caps'] as $cap) {
                $caps[$cap] = true;
            }

            // Roles that can manage events also get the CPT primitive caps.
            if (in_array(self::CAP_MANAGE_EVENTS, $role['caps'], true)) {
                foreach (self::event_caps() as $cap) {
                    $caps[$cap] = true;
                }
            }

            add_role($slug, $role['name'], $caps);
        }

        // Administrators get every TM capability so wp-admin never locks out.
        $admin = get_role('administrator');
        if ($admin) {
            foreach (array_merge(self::all_caps(), self::event_caps()) as $cap) {
                $admin->add_cap($cap);
            }
        }
    }

    /**
     * Remove all roles and admin caps. Called on deactivation.
     */
    public static function remove_roles() {

        foreach (array_keys(self::capabilities()) as $slug) {
            remove_role($slug);
        }

        $admin = get_role('administrator');
        if ($admin) {
            foreach (array_merge(self::all_caps(), self::event_caps()) as $cap) {
                $admin->remove_cap($cap);
            }
        }

        delete_option(self::OPTION_KEY);
    }
}
